# Generated by Django 5.2.13 on 2026-05-02 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('service_id', models.UUIDField()),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('slot_date', models.DateField()),
                ('slot_start', models.TimeField()),
                ('slot_end', models.TimeField()),
                ('session_token', models.TextField()),
                ('capacity_held', models.IntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'slot_holds',
                'ordering': ['slot_date', 'slot_start'],
            },
        ),
    ]
