# Generated by Django 4.2.7 on 2026-05-02 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('slot_start', models.TimeField()),
                ('slot_end', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('capacity_booked', models.IntegerField(default=1)),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('booking_channel', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('voice', 'Voice')], default='web', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confirmation_token', models.CharField(max_length=100, null=True, unique=True)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('no_show_risk_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['slot_date', 'slot_start'],
            },
        ),
        migrations.CreateModel(
            name='BookingAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoShowModelFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_time_hours', models.FloatField()),
                ('day_of_week', models.SmallIntegerField()),
                ('time_of_day_bucket', models.CharField(max_length=20)),
                ('customer_booking_count', models.IntegerField(default=0)),
                ('customer_cancellation_rate', models.FloatField(default=0)),
                ('customer_no_show_rate', models.FloatField(default=0)),
                ('service_cancellation_rate', models.FloatField(default=0)),
                ('booking_channel', models.CharField(default='web', max_length=20)),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('outcome', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(default='pending_payment', max_length=50)),
                ('gateway_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('slot_start', models.TimeField()),
                ('notify_token', models.CharField(max_length=100, null=True, unique=True)),
                ('notify_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
