# Generated by Django 4.2.7 on 2026-05-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_provider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
