# Generated by Django 5.2.13 on 2026-05-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicequestion',
            name='question_type',
            field=models.CharField(choices=[('single_line', 'Single line text'), ('multi_line', 'Multi-line text'), ('phone', 'Phone Number'), ('radio', 'Radio (One Answer)'), ('checkbox', 'Checkboxes (Multiple Answers)')], default='single_line', max_length=50),
        ),
    ]
