# Generated by Django 5.2.13 on 2026-05-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicequestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='booking_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cancellation_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='confirmation_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='intro_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='manual_confirmation_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
