# Generated by Django 4.2.7 on 2026-05-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_booking_fee_service_cancellation_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meeting_auto_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='online_meeting_provider',
            field=models.CharField(choices=[('none', 'None'), ('google_meet', 'Google Meet'), ('zoom', 'Zoom')], default='none', max_length=20),
        ),
    ]
