# Generated by Django 4.2.7 on 2026-05-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_meeting_auto_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='online_meeting_provider',
            field=models.CharField(choices=[('none', 'None'), ('jitsi', 'Jitsi Meet'), ('zoom', 'Zoom')], default='none', max_length=20),
        ),
    ]
