# Generated by Django 4.2.7 on 2026-05-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity_per_slot',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='excluded_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='schedule_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='service',
            name='schedule_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='working_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='working_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
