# Generated by Django 4.2.7 on 2026-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_capacity_per_slot_service_excluded_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
