# Generated by Django 5.2.13 on 2026-05-02 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('call_sid', models.TextField(unique=True)),
                ('phone_number', models.TextField()),
                ('language', models.TextField(default='en')),
                ('session_state', models.JSONField(default=dict)),
                ('current_step', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voice_sessions',
                'indexes': [models.Index(fields=['call_sid'], name='voice_sessi_call_si_f366c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsappSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('phone_number', models.TextField()),
                ('session_state', models.JSONField(default=dict)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'whatsapp_sessions',
                'indexes': [models.Index(fields=['phone_number'], name='whatsapp_se_phone_n_484ed9_idx')],
            },
        ),
    ]
