# Generated by Django 5.2.13 on 2026-05-02 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField()),
                ('question_id', models.UUIDField()),
                ('answer_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookings_bookinganswer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('service_id', models.UUIDField()),
                ('question_text', models.TextField()),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('question_type', models.TextField(default='text')),
                ('options', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'services_servicequestion',
                'ordering': ['display_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('first_name', models.TextField(default='')),
                ('last_name', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('role', models.TextField(default='customer')),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('timezone', models.TextField(default='Asia/Kolkata')),
                ('whatsapp_opted_in', models.BooleanField(default=False)),
                ('google_calendar_connected', models.BooleanField(default=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.TextField(unique=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('preferred_language', models.TextField(default='en')),
                ('emergency_contact', models.TextField(blank=True, null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('custom_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_profiles',
            },
        ),
    ]
